# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
x = np.array([15, 200, 3, 10, 50])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
x.sort()
print(x)

[  3  10  15  50 200]


# Problem 2

In [9]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.array([10, 15, 30, 45, 60])
print(a)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b = np.arange(5, 15)
print(b)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c = np.arange(50, 101, 5)
print(c)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d = np.zeros(10)
print(d)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
e = np.ones(10)
print(e)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f = np.linspace(0, 100, 5)
print(f)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
g = np.random.randint(10, 30, 5)
print(g)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
h = np.random.randint(-1, 2, 10)
print(h)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris = np.random.randint(10, 50, size=(3,5))
print("Matris:\n", matris)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplam = matris.sum(axis=1)
sutun_toplam = matris.sum(axis=0)
print("Satır toplamları:", satir_toplam)
print("Sütun toplamları:", sutun_toplam)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
en_buyuk = matris.max()
en_kucuk = matris.min()
ortalama = matris.mean()
print("En büyük değer:", en_buyuk)
print("En küçük değer:", en_kucuk)
print("Ortalama değer:", ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
indeks = np.argmax(matris) #Numpy içindeki en büyük değerin indeksini bulur. Bunu yaparken matrisi tek boyutlu (flat) gibi değerlendirir.
print("En büyük değerin indeksi:", indeks)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
k = np.arange(10, 21)
print("k dizisinin ilk üç elemanı: " , k[:3]  )

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
l = k[::-1]
print(l)

# 15- Üretilen matrisin ilk satırını seçiniz.
print(matris[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(matris[1, 2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matris[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
kare_matris = np.square(matris)
print("Kare matris:\n", kare_matris)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
yeni_matris = np.random.randint(-50, 51, size=(3, 5))
print("Yeni Matris:\n", yeni_matris)
pozitif_cift = yeni_matris[(yeni_matris > 0) & (yeni_matris % 2 == 0)]
print("Pozitif çift sayılar:", pozitif_cift)

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[14 14 11 21 21]
[-1  0  1  1 -1  1  0  1  0 -1]
Matris:
 [[45 37 39 29 41]
 [13 40 32 35 33]
 [29 38 48 43 29]]
Satır toplamları: [191 153 187]
Sütun toplamları: [ 87 115 119 107 103]
En büyük değer: 48
En küçük değer: 13
Ortalama değer: 35.4
En büyük değerin indeksi: 12
k dizisinin ilk üç elemanı:  [10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
[45 37 39 29 41]
32
[45 13 29]
Kare matris:
 [[2025 1369 1521  841 1681]
 [ 169 1600 1024 1225 1089]
 [ 841 1444 2304 1849  841]]
Yeni Matris:
 [[ -9 -48  11  49 -31]
 [-26 -29 -10  36   3]
 [ 28 -41 -17  -4  45]]
Pozitif çift sayılar: [36 28]
