# Problem 1

In [7]:
# 1 - numpy kütüphanesini import edin
import numpy as np  
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.random.randint(0, 10, size=5)
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.shape)
# 4 - matris'i yeniden boyutlandırın
print(a.reshape(5,1))
# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)

[7 2 1 0 7]
(5,)
[[7]
 [2]
 [1]
 [0]
 [7]]
1


# Problem 2

In [13]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
odd_numbers = np.arange(1, 10, 2)
print(odd_numbers)
# 2 - Oluşturduğunuz matrisi parçalayın
x = np.split(odd_numbers, 5)
print(x)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate(x))

[1 3 5 7 9]
[array([1]), array([3]), array([5]), array([7]), array([9])]
[1 3 5 7 9]


In [15]:
#2- için alternatif çözüm
y = np.array_split(odd_numbers, 2)
print(y)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate(y))

[array([1, 3, 5]), array([7, 9])]
[1 3 5 7 9]


# Problem 3

In [ ]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
m = np.arange( 5, 100, 2)
print(m)
n = np.random.choice(m, size=10, replace=False) #Tekrar etmeden seç
print(n)
# 2 - matris'in özelliklerini inceleyin
print(n.shape) # boyut
print(n.ndim) # boyut sayısı
print(n.size) # eleman sayısı
print(n.dtype) # veri tipi

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]
[49 17 63 59 91 55 75 61 57 97]
(10,)
1
10
int64
