In [2]:
#Slicing ile elemanlara erişmek
import numpy as np
a = np.arange(20,30)

In [3]:
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [4]:
print(a[0:3])

[20 21 22]


In [5]:
print(a[:3])

[20 21 22]


In [6]:
print(a[3:])

[23 24 25 26 27 28 29]


In [7]:
print(a[1::2])

[21 23 25 27 29]


In [8]:
print(a[0::2])

[20 22 24 26 28]


In [9]:
print(a[2::2])

[22 24 26 28]


In [10]:
print(a[1::5])

[21 26]


In [11]:
b = np.random.randint(10, size=[5,5])

In [12]:
print(b)

[[7 3 9 6 8]
 [0 9 1 7 2]
 [8 5 2 5 1]
 [8 1 9 1 2]
 [1 7 9 4 1]]


In [13]:
print(b[:,1])

[3 9 5 1 7]


In [14]:
print(b[:,0])

[7 0 8 8 1]


In [15]:
print(b[0,:])

[7 3 9 6 8]


In [16]:
print(b[1,:])

[0 9 1 7 2]


In [17]:
print(b[0:2,0:3])

[[7 3 9]
 [0 9 1]]


In [18]:
print(b[::2, ::2])

[[7 9 8]
 [8 2 1]
 [1 9 1]]


In [19]:
#Alt küme üzerinde işlem yapmak
alt_b = b[0:3, 0:2]
alt_b

array([[7, 3],
       [0, 9],
       [8, 5]], dtype=int32)

In [20]:
alt_b[0,0] =100

In [21]:
alt_b[1,1] = 200
alt_b

array([[100,   3],
       [  0, 200],
       [  8,   5]], dtype=int32)

In [22]:
print(b)

[[100   3   9   6   8]
 [  0 200   1   7   2]
 [  8   5   2   5   1]
 [  8   1   9   1   2]
 [  1   7   9   4   1]]


In [23]:
#Fancy Index
v = np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [24]:
yetgen = [1,3,5]
print(v[yetgen])

[ 3  9 15]


In [26]:
m =np.arange(9).reshape(3,3)
print(m)
satir = np.array([0,1])
sutun = np.array([1,2])
print(m[satir, sutun])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 5]
