In [1]:
#Klasik Yöntem
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
print(ab)

[2, 6, 12, 20]


In [2]:
#Numpy ile
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
print(a * b)


[ 2  6 12 20]


In [3]:
#.reshape() fonksiyonu ile arraylerin boyutunu değiştirebiliriz.
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
multi = x.reshape(3,3)
print(multi)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#.shape ile arrayin boyutunu öğrenebiliriz.
print(multi.shape)
print(x.shape)

(3, 3)
(9,)


In [5]:
#.ndim ile arrayin kaç boyutlu olduğunu öğrenebiliriz.
print(multi.ndim)
print(x.ndim)

2
1
