In [5]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
z= np.array([11, 12, 13, 14, 15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [8]:
#axis = 0 ise satır bazında birleştirme yapar
#axis = 1 ise sütun bazında birleştirme yapar
print(np.concatenate([a,a], axis = 1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [12]:
m = np.array([1, 2, 3, 99, 99, 3, 2, 1])
print(np.split(m, [3, 5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [13]:
a,b,c = np.split(m, [3, 5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


In [14]:
n = np.arange(16).reshape(4, 4)
np.vsplit(n, 2) #dikey olarak iki parçaya ayırır

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [16]:
np.hsplit(n, 2) #yatay olarak iki parçaya ayırır

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]